### ISSUE TITLE
Please update - Backend implemention on firebase.

### ISSUE THREAD

**Issue by prohealthbox** [mjunaidsalaat/TheFoodShop#5] opened 2018-02-26 08:59 UTC
Hi ,

For newbies like me , your app is really good to learn.
Please update setting up Backend implemention on firebase.
or JSON file.

Thanks,
Arjun

**Comment by JSalaat** [comment] 2018-03-05 13:21
Hey @prohealthbox Arjun,

Thanks for the compliment. I'll surely update this ASAP when I get some time.

Thanks
JSalaat

**Comment by JSalaat** [comment] 2018-03-12 06:56
@SdSalaat Please look into this issue and close this once it is resolved.

**Comment by SdSalaat** [comment] 2018-03-17 10:14
@prohealthbox  The issue is resolved Please Check it now because the merge request is also accepted in master branch

**Closed as completed** 2018-04-04 11:16 UTC
Labels: bug
